# Site settings
title: FrameBit
email: emily@framebit.org
description: > # this means to ignore newlines until "baseurl:"
  Emily May Curtin is an artist and a software engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://framebit.org" # the base hostname & protocol for your site
twitter_username: emilymaycurtin
github_username:  ecurtin

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  art:
    output: true
    permalink: /art/:path/
  tech:
    output: true
    permalink: /tech/:path/
