# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FrameBit
email: emily@framebit.org
description: > # this means to ignore newlines until "baseurl:"
  Emily May Curtin is an artist and a software engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://framebit.org" # the base hostname & protocol for your site
twitter_username: emilymaycurtin
github_username:  ecurtin

excerpt: <!--more-->

# Collections, everything but the blog
collections:
  photos:
    output: true
    permalink: /photos/:path/
  art:
    output: true
    permalink: /art/:path/
  tech:
    output: true
    permalink: /tech/:path/
  film:
    output: true
    permalink: /film/:path/

# Build settings
kramdown:
  input: GFM
