baseURL = 'https://framebit.org/'
languageCode = 'en-us'
title = 'Emily May Curtin'
copyright = "Copyright © 2011-2023, Emily Curtin, all rights reserved."

pluralizeListTitles = "false"

[author]
    name = "Emily May Curtin"
    location = "Atlanta"

[params]
    github_user = "ecurtin"
    github_repo = "https://github.com/ecurtin/framebit"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
