baseURL = 'https://framebit.org/'
languageCode = 'en-us'
title = 'Emily May Curtin'
copyright = "Copyright © 2011-2024, Emily Curtin, all rights reserved."

pluralizeListTitles = false

[params]
    github_user = "ecurtin"
    github_repo = "https://github.com/ecurtin/framebit"
    github_banner = true

    favicon = "favicon.ico"
    author = "Emily May Curtin"
    location = "Atlanta"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.extensions]
      typographer = true
