baseURL = 'https://framebit.org/'
languageCode = 'en-us'
title = 'Emily May Curtin'

author = "Emily May Curtin"
copyright = "Copyright © 2011-2023, Emily Curtin, all rights reserved."

[params]
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    github_user = "dirkolbrich"
    github_repo = "https://github.com/dirkolbrich/hugo-tailwindcss-starter-theme"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
