# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b844ab32a90179e6f4e5f162f9f506639c31084e619da7b7c057345d7a0c9b418f6cb7ef1262b771eb2e181d0c37aa3ac4f235f58450ec372673edfa01223c64

test:
  secret_key_base: 8e7cbe2309d7b89b26ad407d8cf480c1b8e5d6bd5b1991360ee672eba7b75f4c87de39be1ed9bceeefa1ab2971f782e4fa0bdeb2f858b953c9be9854d1667f1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
